In [1]:
import pandas as pd
import numpy as np

In [2]:
# 넘파이 객체(Numpy Object)
# 배열(Array) : 적은 메모리로 많은 데이터를 빠르게 처리 가능
# 파이썬에서 배열을 사용하기 위하 표준 패키지
# 벡터와 행렬을 사용하는 선형대수 계산에 많이 사용

In [3]:
# 배열(Array)
# 같은 타입의 변수들로 이루어진 유한 집합(인덱스 - 데이터)
# 1차원 배열과 2차원 배열
# 다차원의 배열 자료구조 클래스 ndarray
# 1차원 배열
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
# ndim : 배열의 차원
print(array1.shape)
print(type(array1),array1.ndim)

(3,)
<class 'numpy.ndarray'> 1


In [5]:
# 2차원 배열
array2 = np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(array2.shape)
print(type(array2),array2.ndim)

(2, 3)
<class 'numpy.ndarray'> 2


In [7]:
array3 = np.array([[1,2,3]])
array3

array([[1, 2, 3]])

In [8]:
print(array3.shape)
print(type(array3),array3.ndim)

(1, 3)
<class 'numpy.ndarray'> 2


In [9]:
# 배열(array) : 기초 통계 활용
x = np.array([18,5,10,23,19,-8,10,0,0,5,2,15,8,2,5,4,15,-1,4,-7,-24,7,9,-6,23,13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23,  13])

In [10]:
print(np.mean(x))
print(np.var(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))
print(np.median(x))
print(np.percentile(x,25))
print(np.percentile(x,75))

5.8076923076923075
104.61686390532545
10.22823855340329
23
-24
5.0
0.5
12.25


In [11]:
# arange() : 연속되거나 일정한 규칙을 가진 숫자 생성
a = np.arange(10)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [12]:
b = np.arange(1,20,3)
print(b)
print(type(b))
print(b.shape,b.ndim)

[ 1  4  7 10 13 16 19]
<class 'numpy.ndarray'>
(7,) 1


In [13]:
# zeros() : 모든 원소가 0인 행렬 생성
zero_mz = np.zeros((2,3))
print(zero_mz)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# ones(): 모든 원소가 1인 행렬 생성
one_mx = np.ones((3,2))
print(one_mx)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
# full(): 원하는 수의 행렬 생성
full_mx = np.full((3,4),2)
print(full_mx)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [16]:
# random(): 랜덤의 수를 가지는 행렬 생성
random_mx = np.random.random((3,4))
print(random_mx)

[[0.08039773 0.58519824 0.28516102 0.41272025]
 [0.08686338 0.81926197 0.78898608 0.02268168]
 [0.70069504 0.4366758  0.75549413 0.47778695]]


In [17]:
# reshape(): 배열 차원을 재구조화 및 변경
# -1: 변경된 배열의 '-1' 위치의 차원은 자동으로 추정
# \n: 개행 문자, 줄을 바꾼다
array1 = np.arange(12)
print('array1:\n', array1)

array1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
array2 = array1.reshape(3,4)
print('array2:\n',array2)

array2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
array3 = array1.reshape(3,4,order='F')
print('array3:\n',array3)

array3:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [20]:
array1 = np.arange(10)
array2 = array1.reshape(-1,5)

print(array2)
print('array2 ndim:',array2.ndim)
print('array2 shape:',array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 ndim: 2
array2 shape: (2, 5)


In [21]:
array1 = np.arange(10)
array2 = array1.reshape(5,-1)

print(array2)
print('array2 ndim:',array2.ndim)
print('array2 shape:',array2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array2 ndim: 2
array2 shape: (5, 2)


In [22]:
# 인덱싱(1차원 배열)
array1 = np.arange(1,10)
print('array1: ',array1)

print(array1[2])
print(array1[-2])

array1:  [1 2 3 4 5 6 7 8 9]
3
8


In [23]:
array1 = np.arange(1,10)
array2 = array1.reshape(3,3)
print('array2:\n',array2)

print(array2[0,0])
print(array2[-1,-1])
print(array2[-1,-2])

array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8


In [24]:
array1 = np.arange(1,10)
array2 = array1[0:3]
array3 = array1[:3]

print(array1)
print(array2)
print(array3)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3]


In [25]:
array1 = np.arange(1,10)
array2 = array1.reshape(3,3)
print('array2:\n',array2)
print('-'*10)
print(array2[0:2,0:2])
print('-'*10)
print(array2[:2,0])

array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 2]
 [4 5]]
----------
[1 4]
